//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try font.validate()
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    /// Color `AccentColor`.
    static let accentColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AccentColor")
    
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentColor, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 1 files.
  struct file {
    /// Resource file `products.json`.
    static let productsJson = Rswift.FileResource(bundle: R.hostingBundle, name: "products", pathExtension: "json")
    
    /// `bundle.url(forResource: "products", withExtension: "json")`
    static func productsJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.productsJson
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 5 fonts.
  struct font: Rswift.Validatable {
    /// Font `AvertaPE-Bold`.
    static let avertaPEBold = Rswift.FontResource(fontName: "AvertaPE-Bold")
    /// Font `AvertaPE-Light`.
    static let avertaPELight = Rswift.FontResource(fontName: "AvertaPE-Light")
    /// Font `AvertaPE-Regular`.
    static let avertaPERegular = Rswift.FontResource(fontName: "AvertaPE-Regular")
    /// Font `AvertaPE-Semibold`.
    static let avertaPESemibold = Rswift.FontResource(fontName: "AvertaPE-Semibold")
    /// Font `AvertaPE-Thin`.
    static let avertaPEThin = Rswift.FontResource(fontName: "AvertaPE-Thin")
    
    /// `UIFont(name: "AvertaPE-Bold", size: ...)`
    static func avertaPEBold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: avertaPEBold, size: size)
    }
    
    /// `UIFont(name: "AvertaPE-Light", size: ...)`
    static func avertaPELight(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: avertaPELight, size: size)
    }
    
    /// `UIFont(name: "AvertaPE-Regular", size: ...)`
    static func avertaPERegular(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: avertaPERegular, size: size)
    }
    
    /// `UIFont(name: "AvertaPE-Semibold", size: ...)`
    static func avertaPESemibold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: avertaPESemibold, size: size)
    }
    
    /// `UIFont(name: "AvertaPE-Thin", size: ...)`
    static func avertaPEThin(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: avertaPEThin, size: size)
    }
    
    static func validate() throws {
      if R.font.avertaPEBold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'AvertaPE-Bold' could not be loaded, is 'AvertaPE-Bold.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.avertaPELight(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'AvertaPE-Light' could not be loaded, is 'AvertaPE-Light.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.avertaPERegular(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'AvertaPE-Regular' could not be loaded, is 'AvertaPE-Regular.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.avertaPESemibold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'AvertaPE-Semibold' could not be loaded, is 'AvertaPE-Semibold.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.avertaPEThin(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'AvertaPE-Thin' could not be loaded, is 'AvertaPE-Thin.otf' added to the UIAppFonts array in this targets Info.plist?") }
    }
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 1 localization keys.
    struct localizable {
      /// en translation: Products
      /// 
      /// Locales: en
      static let main_bar_title = Rswift.StringResource(key: "main_bar_title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en"], comment: nil)
      
      /// en translation: Products
      /// 
      /// Locales: en
      static func main_bar_title(_: Void = ()) -> String {
        return NSLocalizedString("main_bar_title", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try launchScreen.validate()
      try main.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let mainViewController = StoryboardViewControllerResource<MainViewController>(identifier: "MainViewController")
      let name = "Main"
      
      func mainViewController(_: Void = ()) -> MainViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: mainViewController)
      }
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
        if _R.storyboard.main().mainViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'mainViewController' could not be loaded from storyboard 'Main' as 'MainViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
